# Generated by Django 4.2.23 on 2025-06-13 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Faction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название фракции')),
                ('short_description', models.CharField(max_length=255, verbose_name='Краткое описание')),
            ],
        ),
        migrations.CreateModel(
            name='Metro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название метрополитена')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название станции')),
                ('metro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stations', to='core.metro', verbose_name='Метро')),
            ],
        ),
        migrations.CreateModel(
            name='FactionDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_description', models.TextField(verbose_name='Полное описание')),
                ('faction', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='factiondescription', to='core.faction', verbose_name='Фракция')),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя персонажа')),
                ('factions', models.ManyToManyField(related_name='characters', to='core.faction', verbose_name='Фракции')),
            ],
        ),
    ]
