# Generated by Django 4.2.23 on 2025-06-13 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_character_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
    ]
